server:
  port : 9090

spring:
  application:
    name: report-service
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://collector:4317
    trace-id128: true
    supports-join: false

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

inventoryService:
  baseUrl: ${INVENTORY_BASE_URL:http://localhost:8080}