version: '3.8'
services:
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: 'account'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
    ports:
      - '3306:3306'
    expose:
      - '3306'