apiVersion: v1
kind: Service
metadata:
  name: sample-spring-boot-app-mysql
  labels:
    app: sample-spring-boot-app-mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: sample-spring-boot-app-mysql